language: php

cache:
  directories:
  - $HOME/.composer
  - vendor

php:
- 7.0
- 7.1
- 7.2
- 7.3
- nightly

before_install:
- travis_retry composer self-update

install:
- travis_retry composer update --no-interaction --no-progress --prefer-dist $COMPOSER_FLAGS
